| |
|
|
|go
    func main() {
    }
|
|`go
    func main() {
        a | b || c ||| d
    }
`|
||go
    func main() {
        a | b | c
    }
||
|||go
    func main() {
        a | b || c
    }
|||
| go
    func main() {
    }
|