x -- y
x --- y
x -> y
x --> y
x <- y
x <-- y
x <-> y
x <--> y

super long shape id here --\
    > super long shape id even longer here

super long shape id here --\
    -> super long shape id even longer here

super long shape id here --\
    - super long shape id even longer here

super long shape id here <-\
    - super long shape id even longer here

super long shape id here <-\
    -> super long shape id even longer here

broken multiple times --\
    -\
    \
    \
    > broken multiple times target
broken multiple times --\
    -\
    \
    \
    - broken multiple times target

broken multiple times <-\
    -\
    \
    \
    - broken multiple times target

broken multiple times <-\
    -\
    \
    \
    > broken multiple times target
