imAShape
im_a_shape
im a shape
i'm a shape

i'm \
another \
shape

# notice that one-hyphen is not a connection
# whereas, `a--shape` would be a connection
a-shape
SQLite; Cassandra
pg: PostgreSQL
Cloud: my cloud
Cloud.shape: cloud
a - a
b -\
b
c - \
c
- dash
\
doesn't start with escape
