legalString1: ab
legalString2: a\
b

legalString3: 1
legalString4: 1.1

legalString5: '#111111'
legalString6: "#111111"
legalString7: "#111\
111"

legalString8: ''
legalString9: '\'
legalString10: '\\'
legalString11: '\n'
legalString12: ""
legalString13: "\\"
legalString14: "'"
legalString15: "\""
legalString16: "\n"
legalString17: a|

a.style.stroke: "#694024"
b.style.stroke: '#694024'
c.style.stroke: "#694\
024"
d.style.stroke: "\#694024"
e.style.stroke: "#\694024"
f.style.stroke: "#\694024"
g.style.stroke: "#\A94024"
h.style.stroke: "#\B94024"
i.style.stroke: "#AAA"
j.style.stroke: "#\AAA"

a.style.multiple: false
b.style.multiple: f\
alse
c.style.multiple: fa\
lse
d.style.multiple: fal\
se
e.style.multiple: fals\
e

f.style.multiple: f\
    \
    \
alse

g.style.multiple: true
h.style.multiple: t\
rue
i.style.multiple: tr\
ue
j.style.multiple: tru\
e

a.style.font-size: 10
b.style.font-size: 1\
0

c.style.opacity: 0.4
d.style.opacity: 0\
.5
e.style.opacity: 0.\
6

